import json
from typing import Optional
import anthropic
from ._ai_utils import parse_json_response
from ..config import config
from ..integrations import jira as jira_client


PRIORITY_MAP = {"critical": "Highest", "high": "High", "medium": "Medium", "low": "Low"}


async def _ai_format_bug(
    test_failure: str,
    logs: str,
    environment: str,
) -> dict:
    if not config.ai_configured:
        return {
            "summary": f"Test Failure: {test_failure[:100]}",
            "description": f"Test failed.\n\nLogs:\n{logs[:1000]}",
            "severity": "high",
            "labels": ["automated-qa", "qaforge"],
            "steps_to_reproduce": ["Run the failing test"],
            "root_cause_hypothesis": "Unknown — set ANTHROPIC_API_KEY for AI analysis",
        }

    client = anthropic.AsyncAnthropic(api_key=config.anthropic_api_key)
    prompt = f"""You are a QA engineer creating a bug report. Format the following test failure into a structured bug report.

TEST FAILURE:
{test_failure}

LOGS:
{logs[:3000]}

ENVIRONMENT: {environment}

Respond with JSON only:
{{
  "summary": "Short bug title (max 100 chars)",
  "description": "Detailed description for developers",
  "severity": "critical|high|medium|low",
  "labels": ["label1", "label2"],
  "steps_to_reproduce": ["Step 1...", "Step 2..."],
  "actual_result": "What happened",
  "expected_result": "What should have happened",
  "root_cause_hypothesis": "Likely root cause",
  "affected_component": "Which module/component"
}}"""

    msg = await client.messages.create(
        model=config.claude_model,
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = msg.content[0].text.strip()
    parsed, _ = parse_json_response(raw)
    if parsed is not None:
        return parsed
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {
            "summary": f"Test Failure: {test_failure[:80]}",
            "description": raw,
            "severity": "high",
            "labels": ["automated-qa", "qaforge"],
        }


async def run(
    test_failure: str,
    logs: str = "",
    environment: str = "staging",
    create_jira_ticket: bool = True,
) -> dict:
    bug_data = await _ai_format_bug(test_failure, logs, environment)

    result: dict = {
        "bug_report": bug_data,
        "formatted_report": _format_readable(bug_data, environment),
    }

    if create_jira_ticket:
        jira_priority = PRIORITY_MAP.get(bug_data.get("severity", "high"), "High")
        steps = bug_data.get("steps_to_reproduce", [])
        description_text = (
            f"{bug_data.get('description', '')}\n\n"
            f"Steps to Reproduce:\n" + "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps)) +
            f"\n\nActual Result: {bug_data.get('actual_result', 'See logs')}\n"
            f"Expected Result: {bug_data.get('expected_result', 'Test should pass')}\n\n"
            f"Root Cause Hypothesis: {bug_data.get('root_cause_hypothesis', 'Unknown')}\n\n"
            f"Environment: {environment}\n"
            f"Generated by QAForge MCP"
        )

        jira_result = await jira_client.create_issue(
            summary=bug_data.get("summary", f"Test Failure: {test_failure[:80]}"),
            description=description_text,
            issue_type="Bug",
            priority=jira_priority,
            labels=bug_data.get("labels", ["qaforge"]),
        )
        result["jira_ticket"] = jira_result

    return result


def _format_readable(bug_data: dict, environment: str) -> str:
    lines = [
        f"BUG REPORT",
        f"{'='*50}",
        f"Summary: {bug_data.get('summary', 'N/A')}",
        f"Severity: {bug_data.get('severity', 'N/A').upper()}",
        f"Component: {bug_data.get('affected_component', 'N/A')}",
        f"Environment: {environment}",
        f"",
        f"Description:",
        bug_data.get("description", ""),
        f"",
        f"Steps to Reproduce:",
    ]
    for i, step in enumerate(bug_data.get("steps_to_reproduce", []), 1):
        lines.append(f"  {i}. {step}")
    lines += [
        f"",
        f"Actual Result: {bug_data.get('actual_result', 'See failure logs')}",
        f"Expected Result: {bug_data.get('expected_result', 'Test should pass')}",
        f"",
        f"Root Cause Hypothesis: {bug_data.get('root_cause_hypothesis', 'Unknown')}",
        f"Labels: {', '.join(bug_data.get('labels', []))}",
    ]
    return "\n".join(lines)
